name: CI

on: [push, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#           ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Test
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          ls -l
          echo $SECRET | base64
